org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

mod_id=atomicadditions
mod_name=Mekanism: Atomic Additions
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.lucas.atomicadditions
mod_authors=Lucas
mod_description=An expansion for Mekanism focused on atomic transmutation and advanced ore processing.